compatibility_date = "2024-01-29"
name = "qiita-hackathon-2024-qualify-backend"
send_metrics = false

[[env.dev.d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "qiita-hackathon-2024-qualify"
database_id = "00000000-0000-0000-0000-000000000000"
preview_database_id = "local-test-db"

[[env.production.d1_databases]]
binding = "DB"
database_name = "qiita-hackathon-2024-qualify"
database_id = "ad4a74c2-4d88-4126-a216-1fc288fccf68"

[env.dev.vars]
ENVIROMENT = "dev"

[env.production.vars]
ENVIROMENT = "production"
